# importing the tools we'll use throughout the rest of the script
# pyreadr lets us read in R data foles
import pyreadr
# pandas is a dataframe-managing library and it's the absolute coolest
import pandas as pd
import abcdWrangler as abcdw

# os is more system tools, should also already be installed
# we're importing tools for verifying and manipulating file paths/directories
from os.path import join, isdir
from os import makedirs


OUT_DIR = "/Volumes/projects_herting/LABDOCS/Personnel/Katie/SCEHSC_Pilot/aim3/data"

# if the folder you want to save your dataset in doesn't exist, this will create it for you
if not isdir(OUT_DIR):
    makedirs(OUT_DIR)


ABCD_DIR = "/Volumes/projects_herting/LABDOCS/PROJECTS/ABCD/Data/release5.1/abcd-data-release-5.1"

OUTCOMES = [
    "F4",
    "F5",
    "F6",
    "F3",
    "F2",
    "F1",
    ]

VARS = [
    "dmri_rsirnigm_cdk_bstslh", 
    "dmri_rsirnigm_cdk_caclh", 
    "dmri_rsirnigm_cdk_cmflh", 
    "dmri_rsirnigm_cdk_cnlh", 
    "dmri_rsirnigm_cdk_erlh", 
    "dmri_rsirnigm_cdk_fflh", 
    "dmri_rsirnigm_cdk_iplh", 
    "dmri_rsirnigm_cdk_itlh", 
    "dmri_rsirnigm_cdk_iclh", 
    "dmri_rsirnigm_cdk_lolh", 
    "dmri_rsirnigm_cdk_loflh", 
    "dmri_rsirnigm_cdk_lglh", 
    "dmri_rsirnigm_cdk_moflh", 
    "dmri_rsirnigm_cdk_mtlh", 
    "dmri_rsirnigm_cdk_phlh", 
    "dmri_rsirnigm_cdk_pclh", 
    "dmri_rsirnigm_cdk_poplh", 
    "dmri_rsirnigm_cdk_poblh", 
    "dmri_rsirnigm_cdk_ptglh", 
    "dmri_rsirnigm_cdk_pcclh", 
    "dmri_rsirnigm_cdk_pctlh", 
    "dmri_rsirnigm_cdk_pcglh", 
    "dmri_rsirnigm_cdk_prctlh", 
    "dmri_rsirnigm_cdk_prcnlh", 
    "dmri_rsirnigm_cdk_raclh", 
    "dmri_rsirnigm_cdk_rmflh", 
    "dmri_rsirnigm_cdk_sflh", 
    "dmri_rsirnigm_cdk_splh", 
    "dmri_rsirnigm_cdk_stlh", 
    "dmri_rsirnigm_cdk_smlh", 
    "dmri_rsirnigm_cdk_fplh", 
    "dmri_rsirnigm_cdk_tplh", 
    "dmri_rsirnigm_cdk_ttlh", 
    "dmri_rsirnigm_cdk_islh", 
    "dmri_rsirnigm_cdk_bstsrh", 
    "dmri_rsirnigm_cdk_cacrh", 
    "dmri_rsirnigm_cdk_cmfrh", 
    "dmri_rsirnigm_cdk_cnrh", 
    "dmri_rsirnigm_cdk_errh", 
    "dmri_rsirnigm_cdk_ffrh", 
    "dmri_rsirnigm_cdk_iprh", 
    "dmri_rsirnigm_cdk_itrh", 
    "dmri_rsirnigm_cdk_icrh", 
    "dmri_rsirnigm_cdk_lorh", 
    "dmri_rsirnigm_cdk_lofrh", 
    "dmri_rsirnigm_cdk_lgrh", 
    "dmri_rsirnigm_cdk_mofrh", 
    "dmri_rsirnigm_cdk_mtrh", 
    "dmri_rsirnigm_cdk_phrh", 
    "dmri_rsirnigm_cdk_pcrh", 
    "dmri_rsirnigm_cdk_poprh", 
    "dmri_rsirnigm_cdk_pobrh", 
    "dmri_rsirnigm_cdk_ptgrh", 
    "dmri_rsirnigm_cdk_pccrh", 
    "dmri_rsirnigm_cdk_pctrh", 
    "dmri_rsirnigm_cdk_pcgrh", 
    "dmri_rsirnigm_cdk_prctrh", 
    "dmri_rsirnigm_cdk_prcnrh", 
    "dmri_rsirnigm_cdk_racrh", 
    "dmri_rsirnigm_cdk_rmfrh", 
    "dmri_rsirnigm_cdk_sfrh", 
    "dmri_rsirnigm_cdk_sprh", 
    "dmri_rsirnigm_cdk_strh", 
    "dmri_rsirnigm_cdk_smrh", 
    "dmri_rsirnigm_cdk_fprh", 
    "dmri_rsirnigm_cdk_tprh", 
    "dmri_rsirnigm_cdk_ttrh", 
    "dmri_rsirnigm_cdk_isrh",
    "dmri_rsirndgm_cdk_bstslh", 
    "dmri_rsirndgm_cdk_caclh", 
    "dmri_rsirndgm_cdk_cmflh", 
    "dmri_rsirndgm_cdk_cnlh", 
    "dmri_rsirndgm_cdk_erlh", 
    "dmri_rsirndgm_cdk_fflh", 
    "dmri_rsirndgm_cdk_iplh", 
    "dmri_rsirndgm_cdk_itlh", 
    "dmri_rsirndgm_cdk_iclh", 
    "dmri_rsirndgm_cdk_lolh", 
    "dmri_rsirndgm_cdk_loflh", 
    "dmri_rsirndgm_cdk_lglh", 
    "dmri_rsirndgm_cdk_moflh", 
    "dmri_rsirndgm_cdk_mtlh", 
    "dmri_rsirndgm_cdk_phlh", 
    "dmri_rsirndgm_cdk_pclh", 
    "dmri_rsirndgm_cdk_poplh", 
    "dmri_rsirndgm_cdk_poblh", 
    "dmri_rsirndgm_cdk_ptglh", 
    "dmri_rsirndgm_cdk_pcclh", 
    "dmri_rsirndgm_cdk_pctlh", 
    "dmri_rsirndgm_cdk_pcglh", 
    "dmri_rsirndgm_cdk_prctlh", 
    "dmri_rsirndgm_cdk_prcnlh", 
    "dmri_rsirndgm_cdk_raclh", 
    "dmri_rsirndgm_cdk_rmflh", 
    "dmri_rsirndgm_cdk_sflh", 
    "dmri_rsirndgm_cdk_splh", 
    "dmri_rsirndgm_cdk_stlh", 
    "dmri_rsirndgm_cdk_smlh", 
    "dmri_rsirndgm_cdk_fplh", 
    "dmri_rsirndgm_cdk_tplh", 
    "dmri_rsirndgm_cdk_ttlh", 
    "dmri_rsirndgm_cdk_islh", 
    "dmri_rsirndgm_cdk_bstsrh", 
    "dmri_rsirndgm_cdk_cacrh", 
    "dmri_rsirndgm_cdk_cmfrh", 
    "dmri_rsirndgm_cdk_cnrh", 
    "dmri_rsirndgm_cdk_errh", 
    "dmri_rsirndgm_cdk_ffrh", 
    "dmri_rsirndgm_cdk_iprh", 
    "dmri_rsirndgm_cdk_itrh", 
    "dmri_rsirndgm_cdk_icrh", 
    "dmri_rsirndgm_cdk_lorh", 
    "dmri_rsirndgm_cdk_lofrh", 
    "dmri_rsirndgm_cdk_lgrh", 
    "dmri_rsirndgm_cdk_mofrh", 
    "dmri_rsirndgm_cdk_mtrh", 
    "dmri_rsirndgm_cdk_phrh", 
    "dmri_rsirndgm_cdk_pcrh", 
    "dmri_rsirndgm_cdk_poprh", 
    "dmri_rsirndgm_cdk_pobrh", 
    "dmri_rsirndgm_cdk_ptgrh", 
    "dmri_rsirndgm_cdk_pccrh", 
    "dmri_rsirndgm_cdk_pctrh", 
    "dmri_rsirndgm_cdk_pcgrh", 
    "dmri_rsirndgm_cdk_prctrh", 
    "dmri_rsirndgm_cdk_prcnrh", 
    "dmri_rsirndgm_cdk_racrh", 
    "dmri_rsirndgm_cdk_rmfrh", 
    "dmri_rsirndgm_cdk_sfrh", 
    "dmri_rsirndgm_cdk_sprh", 
    "dmri_rsirndgm_cdk_strh", 
    "dmri_rsirndgm_cdk_smrh", 
    "dmri_rsirndgm_cdk_fprh", 
    "dmri_rsirndgm_cdk_tprh", 
    "dmri_rsirndgm_cdk_ttrh", 
    "dmri_rsirndgm_cdk_isrh",
    "rsfmri_c_ngd_ad_ngd_ad",
    "rsfmri_c_ngd_ad_ngd_cgc",
    "rsfmri_c_ngd_ad_ngd_ca",
    "rsfmri_c_ngd_ad_ngd_dt",
    "rsfmri_c_ngd_ad_ngd_dla",
    "rsfmri_c_ngd_ad_ngd_fo",
    "rsfmri_c_ngd_ad_ngd_rspltp",
    "rsfmri_c_ngd_ad_ngd_smh",
    "rsfmri_c_ngd_ad_ngd_smm",
    "rsfmri_c_ngd_ad_ngd_sa",
    "rsfmri_c_ngd_ad_ngd_vta",
    "rsfmri_c_ngd_ad_ngd_vs",
    "rsfmri_c_ngd_cgc_ngd_cgc",
    "rsfmri_c_ngd_cgc_ngd_ca",
    "rsfmri_c_ngd_cgc_ngd_dt",
    "rsfmri_c_ngd_cgc_ngd_dla",
    "rsfmri_c_ngd_cgc_ngd_fo",
    "rsfmri_c_ngd_cgc_ngd_rspltp",
    "rsfmri_c_ngd_cgc_ngd_smh",
    "rsfmri_c_ngd_cgc_ngd_smm",
    "rsfmri_c_ngd_cgc_ngd_sa",
    "rsfmri_c_ngd_cgc_ngd_vta",
    "rsfmri_c_ngd_cgc_ngd_vs",
    "rsfmri_c_ngd_ca_ngd_ca",
    "rsfmri_c_ngd_ca_ngd_dt",
    "rsfmri_c_ngd_ca_ngd_dla",
    "rsfmri_c_ngd_ca_ngd_fo",
    "rsfmri_c_ngd_ca_ngd_rspltp",
    "rsfmri_c_ngd_ca_ngd_smh",
    "rsfmri_c_ngd_ca_ngd_smm",
    "rsfmri_c_ngd_ca_ngd_sa",
    "rsfmri_c_ngd_ca_ngd_vta",
    "rsfmri_c_ngd_ca_ngd_vs",
    "rsfmri_c_ngd_dt_ngd_dt",
    "rsfmri_c_ngd_dt_ngd_dla",
    "rsfmri_c_ngd_dt_ngd_fo",
    "rsfmri_c_ngd_dt_ngd_rspltp",
    "rsfmri_c_ngd_dt_ngd_smh",
    "rsfmri_c_ngd_dt_ngd_smm",
    "rsfmri_c_ngd_dt_ngd_sa",
    "rsfmri_c_ngd_dt_ngd_vta",
    "rsfmri_c_ngd_dt_ngd_vs",
    "rsfmri_c_ngd_dla_ngd_dla",
    "rsfmri_c_ngd_dla_ngd_fo",
    "rsfmri_c_ngd_dla_ngd_rspltp",
    "rsfmri_c_ngd_dla_ngd_smh",
    "rsfmri_c_ngd_dla_ngd_smm",
    "rsfmri_c_ngd_dla_ngd_sa",
    "rsfmri_c_ngd_dla_ngd_vta",
    "rsfmri_c_ngd_dla_ngd_vs",
    "rsfmri_c_ngd_fo_ngd_fo",
    "rsfmri_c_ngd_fo_ngd_rspltp",
    "rsfmri_c_ngd_fo_ngd_smh",
    "rsfmri_c_ngd_fo_ngd_smm",
    "rsfmri_c_ngd_fo_ngd_sa",
    "rsfmri_c_ngd_fo_ngd_vta",
    "rsfmri_c_ngd_fo_ngd_vs",
    "rsfmri_c_ngd_rspltp_ngd_rspltp",
    "rsfmri_c_ngd_rspltp_ngd_smh",
    "rsfmri_c_ngd_rspltp_ngd_smm",
    "rsfmri_c_ngd_rspltp_ngd_sa",
    "rsfmri_c_ngd_rspltp_ngd_vta",
    "rsfmri_c_ngd_rspltp_ngd_vs",
    "rsfmri_c_ngd_smh_ngd_smh",
    "rsfmri_c_ngd_smh_ngd_smm",
    "rsfmri_c_ngd_smh_ngd_sa",
    "rsfmri_c_ngd_smh_ngd_vta",
    "rsfmri_c_ngd_smh_ngd_vs",
    "rsfmri_c_ngd_smm_ngd_smm",
    "rsfmri_c_ngd_smm_ngd_sa",
    "rsfmri_c_ngd_smm_ngd_vta",
    "rsfmri_c_ngd_smm_ngd_vs",
    "rsfmri_c_ngd_sa_ngd_sa",
    "rsfmri_c_ngd_sa_ngd_vta",
    "rsfmri_c_ngd_sa_ngd_vs",
    "rsfmri_c_ngd_vta_ngd_vta",
    "rsfmri_c_ngd_vta_ngd_vs",
    "rsfmri_c_ngd_vs_ngd_vs",
    "rsfmri_meanmotion",
    "rsfmri_ntpoints",
    "imgincl_rsfmri_include",
    "dmri_meanmotion",
    "imgincl_dmri_include",
    "mrif_score",
    "mri_info_manufacturer",
    "mri_info_deviceserialnumber",
    "interview_date",
    "interview_age",
    'physical_activity1_y',
    "stq_y_ss_weekday", 
    "stq_y_ss_weekend",
]
LED_VARS = [
    "reshist_addr1_proxrd",
    "reshist_addr1_popdensity",
    "reshist_addr1_urban_area",
    "nsc_p_ss_mean_3_items",
    "ehi_y_ss_scoreb",
    'reshist_addr1_Lnight_exi',
    'reshist_addr1_pm252016aa'
]

DEMO_VARS = [
    'race_ethnicity_c_bl',
    'household_income_4bins_bl',
    "site_id_l",
    'rel_family_id',
    "demo_sex_v2_bl"
]
dat = abcdw.data_grabber(ABCD_DIR, VARS, ['baseline_year_1_arm_1','2_year_follow_up_y_arm_1'], multiindex=True)
dat2 = abcdw.data_grabber(ABCD_DIR, LED_VARS, 'baseline_year_1_arm_1')
dat2.index = pd.MultiIndex.from_product([dat2.index, ['baseline_year_1_arm_1']])
demo_df = pyreadr.read_r(
    '/Volumes/projects_herting/LABDOCS/PROJECTS/ABCD/ABCD_Covariates/ABCD_release5.1/01_Demographics/ABCD_5.1_demographics_complete.RDS'
)
demo_df = demo_df[None]
demo_df = demo_df[demo_df['eventname'] == 'baseline_year_1_arm_1']
demo_df.index = pd.MultiIndex.from_arrays([demo_df['src_subject_id'], demo_df['eventname']])
demo_df = demo_df.drop(['src_subject_id', 'eventname'], axis=1)
dat = pd.concat([dat, dat2, demo_df[DEMO_VARS]], axis=1)

pm_factors = pd.read_excel('/Volumes/projects_herting/LABDOCS/Personnel/Kirthana/Project3_particlePM/PMF tool results/Contribution_F6run10_fpeak.xlsx', 
              skiprows=0, index_col=0, header=1)
pm_factors.index = pd.MultiIndex.from_product([pm_factors.index, ['baseline_year_1_arm_1']])

big_df = pd.concat([dat, pm_factors], axis=1)
big_df.to_pickle(join(OUT_DIR, 'data.pkl')
)